---
  title: "Chemical dormancyh"
author: "Kevin D. Webster and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin = 2.54cm
---
  
##An individual based model to examine dormancy, activity, death, birth

```{r setup}
rm(list=ls())
getwd()
#setwd('C:/Current/Dine/Research/AstroDorm/AstroDormCode')
setwd("~/GitHub/astrodorm/")
```

```{r}
require("png")
require("dplyr")
library("tidyverse")
require("grid")
require("tibble")
require("knitr")
require("extrafont")
require("ggrepel");
require("gridExtra")
require("contrast")
sem <- function(x) sqrt(var(x)/length(x))
cv <- function(x) (sd(x)/mean(x))*100
```

# Load OD data

```{r}
AS <- read.csv("data/AverageShielding.csv")

sAS <- AS[c(1, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000),]
x <- c(1, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)
```

# Make figure

```{r}
png(filename="~/GitHub/astrodorm/figures/Fig4b.png",
    width = 1200, height = 1200, res = 96*2) 
plot.new()


# Reduce transparency by 10%, 25%, 50%, 75%
blue_3 <- rgb(0, 0, 1, alpha = 0.8)
blue_2 <- rgb(0, 0, 1, alpha = 0.4)
blue_1 <- rgb(0, 0, 1, alpha = 0.1)

# 2% decay
par(mar = c(7, 7, 5, 7))
plot(x, sAS[,4], xlim = c(-50, 1050), ylim = c(0.02, 420), type = "b", 
     lty = 3, col = "black", lwd = 2, ylab = "", xlab = "", log = "y",
     cex.lab = 1.5, las = 1, yaxt = "n", xaxt = "n", pch = 21, cex = 2, bg = blue_2)
box(lwd = 2)
#segments(x, sAS[,4]-sAS[,5], x ,sAS[,4]+sAS[,5], col = "black", lwd = 2)

# 1% decay
points(x, sAS[,2], type = "b", pch = 21, col = "black", cex = 2, lwd = 2, lty = 3, bg = blue_1)
#segments(x, sAS[,2]-sAS[,3], x, sAS[,2]+sAS[,3], col = "black", lwd = 2)

# 3% decay
points(x, sAS[,6], type = "b", pch = 21, col = "black", cex = 2, lwd = 2, lty = 3, bg = blue_3)
#segments(x, sAS[,6]-sAS[,7], x, sAS[,6]+sAS[,7], col = "black", lwd = 2)

# Add axis ticks and labels
axis(2, at = c(0.1, 1, 10, 100), cex.axis = 1.25,
     labels = expression(10^-1, 10^0, 10^1, 10^2), las = 1)

axis(4, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1.25,
     at = c(10^-1, 10^0, 10^1, 10^2))

axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1, mgp = c(1, 1, 0),
     labels = c("0", "500", "1000"), at = c(0, 500, 1000))

axis(side = 3, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1, 
     at = c(0, 500, 1000))

# Add axis labels

mtext(expression('Total abundance (' * italic(A[a]) + italic(A[i]) * ')'), side = 2, outer = TRUE, cex = 1.5, 
      line = -3, adj = 0.55)

mtext('Time', side = 1, outer = TRUE, cex = 1.5, 
      line = -3, adj = 0.5)

mtext(expression(italic(d) == 1 * "%"), side = 4, line = -5, at = 300, cex = 1.25, las = 2)
mtext(expression(italic(d) == 2 * "%"), side = 4, line = -5, at = 1, cex = 1.25, las = 2)
mtext(expression(italic(d) == 3 * "%"), side = 4, line = -12, at = 0.05, cex = 1.25, las = 2)


#mtext(expression("decay = 3%"), side = 4, line = -1.5, at = 35, cex = 1.25, las = 2)

# Close plot device (completes writing of file)
dev.off()
graphics.off()

# Shows plot in R console window
img <- readPNG("~/GitHub/astrodorm/figures/Fig4b.png")
grid.raster(img)
```





<!-- plot(x, sAS[,4], type = "b", pch = 19, col = rgb(0,1,0, alpha = 0.6),  -->
<!--      ylim=c(0,400), cex = 2, ylab = "Total abudance (Aa + Ai)", -->
<!--      xlab = "Time Step") -->
<!-- segments(x,sAS[,4]-sAS[,5],x,sAS[,4]+sAS[,5], col = rgb(0,1,0, alpha = 0.6)) -->

<!-- points(x, sAS[,2], type = "b", pch = 19, col = rgb(0,0,0, alpha = 0.6), cex = 2) -->
<!-- segments(x,sAS[,2]-sAS[,3],x,sAS[,2]+sAS[,3], col = rgb(0,0,0, alpha = 0.6)) -->

<!-- points(x, sAS[,6], type = "b", pch = 19, col = rgb(1,0,1, alpha = 0.6), cex = 2) -->
<!-- segments(x,sAS[,6]-sAS[,7],x,sAS[,6]+sAS[,7], col = rgb(1,0,1, alpha = 0.6)) -->

<!-- legend(400, 475, title = "Decay in Dormancy", -->
<!--        legend=c("1 %", "2 %", "3 %"), -->
<!--        pch = 19, -->
<!--        col = c(rgb(0,0,0, alpha = 0.6),  -->
<!--                rgb(0,1,0, alpha = 0.6), rgb(1,0,1, alpha = 0.6)), -->
<!--        cex = 1.1, -->
<!--        box.lty = 0, -->
<!--        bg= rgb(1,1,1,0), -->
<!--        y.intersp= 0.5) -->
